name: 3.1 - Test BODS National ZIP

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  Test-BODS-ZIP:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Test BODS national ZIP
        run: bun run bods-zip

      - name: Commit all.json & all-new.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add live/all.json live/all-new.json

          if git diff --cached --quiet; then
            echo "No changes to all.json"
            exit 0
          fi

          git commit -m "Update all BODS vehicle data"
          git push
