name: Run All Fetchers

on:
  workflow_dispatch:

concurrency:
  group: run-all

jobs:
  run-BODS-fetcher:
    name: Run BODS.yml
    uses: ./.github/workflows/BODS.yml

  run-FLIX-fetcher:
    name: Run Flix.yml
    uses: ./.github/workflows/Flix.yml

  run-FALC-fetcher:
    name: Run FALC.yml
    uses: ./.github/workflows/FALC.yml
