name: 3 - Test All Fetchers

on:
  workflow_dispatch:

concurrency:
  group: run-all
  cancel-in-progress: false

jobs:
  run-BODS-ZIP-fetcher:
    name: Run BODS-zip.yml
    uses: ./.github/workflows/BODS-zip.yml
    
  run-BODS-API-fetcher:
    name: Run BODS-API.yml
    uses: ./.github/workflows/BODS-API.yml
    secrets: inherit

  run-FLIX-fetcher:
    name: Run Flix.yml
    uses: ./.github/workflows/Flix.yml

  run-FALC-fetcher:
    name: Run FALC.yml
    uses: ./.github/workflows/FALC.yml
