name: 3.2 - Test Falcon Bus Data

on:
  workflow_dispatch:
  workflow_call: 

jobs:
  Fetch-Falcon-Data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Falcon bus Data
        run: bun run megabus
