name: Falcon Journey Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Fetch Falcon Data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Run Falcon journey scraper
        #run: bun run scripts/get-falcon-journeys.ts
        run: bun scripts/fetch-megabus-new.ts

      - name: Commit updated MegaBus data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/megabus.json
          git diff --cached --quiet || git commit -m "Update MegaBus journey data"
          git push

# https://megabus.tmpanel.co.uk/Tracker/GetJourney
# https://megabus.tmpanel.co.uk/Tracker/GetJourneyStage
